# Generated by Django 5.1.3 on 2024-11-13 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('web_dev', 'Web Development'), ('data', 'Data Science/Machine Learning'), ('script', 'Scripts/Automation'), ('personal', 'Personal Project')], default='personal', max_length=128),
        ),
        migrations.AlterField(
            model_name='project',
            name='link',
            field=models.URLField(),
        ),
    ]
